name: competition_app
description: A Flutter project for sports competition search with geolocation mapping.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  sqflite: ^2.3.2
  provider: ^6.1.2
  path_provider: ^2.1.2
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0  # Added for efficient image loading of team logos

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env  # Include the .env file as an asset